dbt_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: dados_prod
      schema: silver
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
